import pytest
import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.pyramid import Pyramid, PyramidNode
from app.models.ai_suggestion import AISuggestion
from app.services.suggestion_executor import suggestion_executor
from app.services.pyramid_service import PyramidService
from app.schemas.pyramid import PyramidCreate, PyramidNodeCreate

@pytest.mark.asyncio
async def test_suggestion_executor_create_node(db_session: AsyncSession):
    # Setup
    db = db_session
    pyramid = Pyramid(name="Test Pyramid Create", description="Test Description")
    db.add(pyramid)
    await db.commit()
    await db.refresh(pyramid)
    
    # Create Suggestion
    params = {
        "pyramid_id": str(pyramid.id),
        "name": "New Node",
        "description": "Generated by AI",
        "parent_id": None
    }
    suggestion = AISuggestion(
        pyramid_id=pyramid.id,
        action_type="create_node",
        params=params,
        status="pending"
    )
    db.add(suggestion)
    await db.commit()
    await db.refresh(suggestion)
    
    # Execute
    result = await suggestion_executor.execute(str(suggestion.id), db)
    
    # Verify
    assert result["success"] is True
    assert result["data"]["action"] == "create_node"
    
    # Check Node in DB
    service = PyramidService(db)
    nodes = await service.get_nodes(pyramid.id)
    created_node = next((n for n in nodes if n.name == "New Node"), None)
    assert created_node is not None
    assert created_node.description == "Generated by AI"

@pytest.mark.asyncio
async def test_suggestion_executor_split_node_with_description(db_session: AsyncSession):
    # Setup
    db = db_session
    pyramid = Pyramid(name="Test Pyramid Split", description="Test Description")
    db.add(pyramid)
    await db.commit()
    await db.refresh(pyramid)
    
    node = PyramidNode(pyramid_id=pyramid.id, name="To Split", path="/")
    db.add(node)
    await db.commit()
    await db.refresh(node)
    
    # Create Suggestion
    params = {
        "node_id": str(node.id),
        "suggested_children": ["Child A", "Child B"]
        # Note: Current implementation only supports list of strings for names
        # We want to support list of dicts with descriptions later
    }
    suggestion = AISuggestion(
        pyramid_id=pyramid.id,
        target_id=node.id,
        target_type="pyramid_node",
        action_type="split_node",
        params=params,
        status="pending"
    )
    db.add(suggestion)
    await db.commit()
    await db.refresh(suggestion)
    
    # Execute
    result = await suggestion_executor.execute(str(suggestion.id), db)
    
    # Verify
    assert result["success"] is True
    
    # Check Children
    service = PyramidService(db)
    children = await service._get_node_children(node.id)
    assert len(children) == 2
    assert any(c.name == "Child A" for c in children)
    assert any(c.name == "Child B" for c in children)

@pytest.mark.asyncio
async def test_suggestion_executor_move_node_recursive(db_session: AsyncSession):
    # Setup
    db = db_session
    pyramid = Pyramid(name="Test Pyramid Move", description="Test Description")
    db.add(pyramid)
    await db.commit()
    await db.refresh(pyramid)
    
    # Create Structure: Root -> Parent -> Child -> Grandchild
    root = PyramidNode(pyramid_id=pyramid.id, name="Root", path="/", level=0)
    db.add(root)
    await db.commit()
    await db.refresh(root)
    
    parent = PyramidNode(pyramid_id=pyramid.id, name="Parent", parent_id=root.id, path=f"/{root.id}/", level=1)
    db.add(parent)
    await db.commit()
    await db.refresh(parent)
    
    child = PyramidNode(pyramid_id=pyramid.id, name="Child", parent_id=parent.id, path=f"/{root.id}/{parent.id}/", level=2)
    db.add(child)
    await db.commit()
    await db.refresh(child)

    grandchild = PyramidNode(pyramid_id=pyramid.id, name="Grandchild", parent_id=child.id, path=f"/{root.id}/{parent.id}/{child.id}/", level=3)
    db.add(grandchild)
    await db.commit()
    await db.refresh(grandchild)
    
    # New Parent (Sibling of Parent)
    new_parent = PyramidNode(pyramid_id=pyramid.id, name="New Parent", parent_id=root.id, path=f"/{root.id}/", level=1)
    db.add(new_parent)
    await db.commit()
    await db.refresh(new_parent)
    
    # Create Suggestion: Move Child to New Parent
    params = {
        "node_id": str(child.id),
        "target_parent_id": str(new_parent.id)
    }
    suggestion = AISuggestion(
        pyramid_id=pyramid.id,
        target_id=child.id,
        target_type="pyramid_node",
        action_type="move_node",
        params=params,
        status="pending"
    )
    db.add(suggestion)
    await db.commit()
    await db.refresh(suggestion)
    
    # Execute
    result = await suggestion_executor.execute(str(suggestion.id), db)
    
    # Verify
    assert result["success"] is True
    
    # Check Paths
    await db.refresh(child)
    await db.refresh(grandchild)
    
    expected_child_path = f"/{root.id}/{new_parent.id}/"
    assert child.parent_id == new_parent.id
    assert child.path == expected_child_path
    
    # This assertion is expected to FAIL with current implementation
    expected_grandchild_path = f"/{root.id}/{new_parent.id}/{child.id}/"
    assert grandchild.path == expected_grandchild_path
