"""Add contribution and synonym models

Revision ID: 0535bb7f91a8
Revises: 912e7d453313
Create Date: 2026-02-14 00:52:04.274652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0535bb7f91a8'
down_revision = '912e7d453313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonym_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_term', sa.String(length=100), nullable=False),
    sa.Column('synonym', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synonym_mappings'))
    )
    with op.batch_alter_table('synonym_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_synonym_mappings_canonical_term'), ['canonical_term'], unique=False)
        batch_op.create_index(batch_op.f('ix_synonym_mappings_synonym'), ['synonym'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('original_input', sa.Text(), nullable=False),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('extracted_concepts', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_contributions_content_id_content_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributions'))
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_status'), ['status'], unique=False)

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_status'))

    op.drop_table('contributions')
    with op.batch_alter_table('synonym_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_synonym_mappings_synonym'))
        batch_op.drop_index(batch_op.f('ix_synonym_mappings_canonical_term'))

    op.drop_table('synonym_mappings')
    # ### end Alembic commands ###
