"""Add Iteration 5 models

Revision ID: 1f0b07462199
Revises: 82e338d8125c
Create Date: 2026-02-12 17:24:18.697848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0b07462199'
down_revision = '82e338d8125c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_metrics'))
    )
    op.create_table('error_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('source_service', sa.String(length=50), nullable=False),
    sa.Column('source_task_id', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_records'))
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('min_level', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_allow_critical', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channels_sent', sa.JSON(), nullable=False),
    sa.Column('webhook_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['prompt_versions.id'], name=op.f('fk_prompt_templates_current_version_id_prompt_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('scene', name=op.f('uq_prompt_templates_scene'))
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('avg_quality_score', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], name=op.f('fk_prompt_versions_template_id_prompt_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions'))
    )
    op.create_table('ab_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version_a_id', sa.Uuid(), nullable=False),
    sa.Column('version_b_id', sa.Uuid(), nullable=False),
    sa.Column('traffic_ratio', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_a_calls', sa.Integer(), nullable=False),
    sa.Column('version_b_calls', sa.Integer(), nullable=False),
    sa.Column('version_a_avg_quality', sa.Float(), nullable=False),
    sa.Column('version_b_avg_quality', sa.Float(), nullable=False),
    sa.Column('winner_version_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], name=op.f('fk_ab_tests_template_id_prompt_templates')),
    sa.ForeignKeyConstraint(['version_a_id'], ['prompt_versions.id'], name=op.f('fk_ab_tests_version_a_id_prompt_versions')),
    sa.ForeignKeyConstraint(['version_b_id'], ['prompt_versions.id'], name=op.f('fk_ab_tests_version_b_id_prompt_versions')),
    sa.ForeignKeyConstraint(['winner_version_id'], ['prompt_versions.id'], name=op.f('fk_ab_tests_winner_version_id_prompt_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_tests'))
    )
    
    # ### Manual additions ###
    
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        # Enable pg_trgm extension
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # Content Search
    # Note: pg_trgm requires PostgreSQL. If using SQLite, these might fail or be ignored if we wrap in try-except or check dialect.
    # For now, assuming PostgreSQL as per requirements.
    # op.create_index('idx_content_items_title_trgm', 'content_items', ['title'], postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # op.create_index('idx_content_items_summary_trgm', 'content_items', ['summary'], postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    
    # Since we might be running locally on SQLite (dev) or Postgres (prod), we should be careful.
    # But Requirements say "PostgreSQL pg_trgm 扩展", so I will add it.
    # To be safe for SQLite dev environment, I'll check bind dialect or just add them (SQLite will error on 'gin').
    
    if bind.engine.name == 'postgresql':
        op.create_index('idx_content_items_title_trgm', 'content_items', ['title'], postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
        op.create_index('idx_content_items_summary_trgm', 'content_items', ['summary'], postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
        op.create_index('idx_error_records_unresolved', 'error_records', ['is_resolved', sa.text('created_at DESC')], postgresql_where=sa.text('is_resolved = false'))
        op.create_index('idx_notifications_unread', 'notifications', ['is_read', sa.text('created_at DESC')], postgresql_where=sa.text('is_read = false'))
    else:
        # SQLite fallbacks or skips
        op.create_index('idx_content_items_title', 'content_items', ['title'])
        # Partial indexes not fully supported in old SQLite or via simple syntax in some versions, but standard CREATE INDEX ... WHERE works in newer SQLite.
        # However, SQLAlchemy/Alembic support might vary. I'll just skip partial/special indexes for SQLite to avoid breaking dev if it uses SQLite.
        pass

    op.create_index('idx_validation_results_overall_score', 'validation_results', [sa.text('overall_score DESC')])
    op.create_index('idx_content_items_status', 'content_items', ['status'])

    # Information Source
    op.create_index('idx_sources_status_health', 'information_sources', ['status', sa.text('health_score DESC')])

    # API Metrics
    op.create_index('idx_api_metrics_endpoint_time', 'api_metrics', ['endpoint', sa.text('created_at DESC')])
    op.create_index('idx_api_metrics_created_at', 'api_metrics', [sa.text('created_at DESC')])

    # Error Records
    op.create_index('idx_error_records_type_time', 'error_records', ['error_type', sa.text('created_at DESC')])

    # Prompt Versions
    op.create_index('idx_prompt_versions_template', 'prompt_versions', ['template_id', sa.text('version DESC')])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual drops
    op.drop_index('idx_sources_status_health', table_name='information_sources')
    op.drop_index('idx_content_items_status', table_name='content_items')
    op.drop_index('idx_validation_results_overall_score', table_name='validation_results')
    
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.drop_index('idx_content_items_summary_trgm', table_name='content_items')
        op.drop_index('idx_content_items_title_trgm', table_name='content_items')
        op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    else:
        op.drop_index('idx_content_items_title', table_name='content_items')

    op.drop_table('ab_tests')
    op.drop_table('prompt_versions')
    op.drop_table('prompt_templates')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_table('error_records')
    op.drop_table('api_metrics')
    # ### end Alembic commands ###
