"""add_content_metabolism_fields

Revision ID: 21819aba214f
Revises: 65f0e2730b55
Create Date: 2026-02-14 11:33:43.882369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21819aba214f'
down_revision = '65f0e2730b55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifecycle_status', sa.String(length=20), server_default='ACTIVE', nullable=False))
        batch_op.add_column(sa.Column('metabolism_score', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('access_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_content_items_last_accessed_at'), ['last_accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_lifecycle_status'), ['lifecycle_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_metabolism_score'), ['metabolism_score'], unique=False)

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_metabolism_score'))
        batch_op.drop_index(batch_op.f('ix_content_items_lifecycle_status'))
        batch_op.drop_index(batch_op.f('ix_content_items_last_accessed_at'))
        batch_op.drop_column('access_count')
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('metabolism_score')
        batch_op.drop_column('lifecycle_status')

    # ### end Alembic commands ###
