"""add_whitelist_and_discovered_domain

Revision ID: 25303b564393
Revises: ebdc791cf851
Create Date: 2026-02-12 14:32:06.047743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25303b564393'
down_revision = 'ebdc791cf851'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL_SUCCESS', name='batchtaskstatus'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_tasks'))
    )
    op.create_table('domain_whitelists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('credibility', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_whitelists'))
    )
    with op.batch_alter_table('domain_whitelists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_whitelists_domain'), ['domain'], unique=True)

    op.create_table('discovered_domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('evaluation_status', sa.String(length=20), nullable=False),
    sa.Column('has_rss', sa.Boolean(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['approvals.id'], name=op.f('fk_discovered_domains_proposal_id_approvals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_domains'))
    )
    with op.batch_alter_table('discovered_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_domains_domain'), ['domain'], unique=True)

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_analysis', sa.JSON(), nullable=True))

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('pyramids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyramids', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_column('impact_analysis')

    with op.batch_alter_table('discovered_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_domains_domain'))

    op.drop_table('discovered_domains')
    with op.batch_alter_table('domain_whitelists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_whitelists_domain'))

    op.drop_table('domain_whitelists')
    op.drop_table('batch_tasks')
    # ### end Alembic commands ###
