"""Add Iteration 3 models

Revision ID: 380c488b41f4
Revises: ed9955770bf2
Create Date: 2026-02-12 10:08:53.069838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380c488b41f4'
down_revision = 'ed9955770bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_approvals_source_content_id_content_items'), 'content_items', ['source_content_id'], ['id'])

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('input_type', sa.String(length=20), server_default='url', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('input_type')
        batch_op.drop_column('submitter_id')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_approvals_source_content_id_content_items'), type_='foreignkey')

    # ### end Alembic commands ###
