"""add_ai_fields_to_content_item

Revision ID: 5d78fcb79c09
Revises: 816be15f74ff
Create Date: 2026-02-13 13:04:35.585638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d78fcb79c09'
down_revision = '816be15f74ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts'))
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_name'), ['name'], unique=False)

    op.create_table('concept_synonyms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('synonym', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_concept_synonyms_concept_id_concepts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_synonyms'))
    )
    with op.batch_alter_table('concept_synonyms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_synonyms_synonym'), ['synonym'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pyramid_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pyramid_id'], ['pyramids.id'], name=op.f('fk_snapshots_pyramid_id_pyramids')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots'))
    )
    with op.batch_alter_table('api_metrics', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_api_metrics_created_at'))
        # batch_op.drop_index(batch_op.f('idx_api_metrics_endpoint_time'))
        pass

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concepts', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_processed', sa.Boolean(), server_default='false', nullable=False))
        # batch_op.drop_index(batch_op.f('idx_content_items_status'))
        # batch_op.drop_index(batch_op.f('idx_content_items_title'))

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_error_records_type_time'))
        pass

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_sources_status_health'))
        pass

    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_prompt_versions_template'))
        pass

    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_validation_results_overall_score'))
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_validation_results_overall_score'), ['overall_score'], unique=False)

    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_prompt_versions_template'), ['template_id', 'version'], unique=False)

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sources_status_health'), ['status', 'health_score'], unique=False)

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_error_records_type_time'), ['error_type', 'created_at'], unique=False)

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_content_items_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('idx_content_items_status'), ['status'], unique=False)
        batch_op.drop_column('ai_processed')
        batch_op.drop_column('concepts')

    with op.batch_alter_table('api_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_metrics_endpoint_time'), ['endpoint', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_metrics_created_at'), ['created_at'], unique=False)

    op.drop_table('snapshots')
    with op.batch_alter_table('concept_synonyms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_synonyms_synonym'))

    op.drop_table('concept_synonyms')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_name'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
