"""add_source_error_fields

Revision ID: 65663b1db439
Revises: b976ad19c455
Create Date: 2026-02-12 09:14:00.698458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65663b1db439'
down_revision = 'b976ad19c455'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information_sources', sa.Column('error_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('information_sources', sa.Column('last_error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('information_sources', 'last_error_message')
    op.drop_column('information_sources', 'error_count')
    # ### end Alembic commands ###
