"""Add node_type to PyramidNode

Revision ID: 73190a229726
Revises: 112233445566
Create Date: 2026-02-20 20:18:03.476785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '73190a229726'
down_revision = '112233445566'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('prompt_templates')
    # op.drop_table('ab_tests')
    # op.drop_table('prompt_versions')
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.drop_column('node_type')

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # op.create_table('prompt_versions',
    # sa.Column('id', sa.CHAR(length=32), nullable=False),
    # sa.Column('template_id', sa.CHAR(length=32), nullable=False),
    # sa.Column('version', sa.INTEGER(), nullable=False),
    # sa.Column('content', sa.TEXT(), nullable=False),
    # sa.Column('variables', sqlite.JSON(), nullable=False),
    # sa.Column('call_count', sa.INTEGER(), nullable=False),
    # sa.Column('avg_latency_ms', sa.FLOAT(), nullable=False),
    # sa.Column('avg_quality_score', sa.FLOAT(), nullable=False),
    # sa.Column('error_rate', sa.FLOAT(), nullable=False),
    # sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('created_by', sa.VARCHAR(length=100), nullable=False),
    # sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], name=op.f('fk_prompt_versions_template_id_prompt_templates')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions'))
    # )
    # op.create_table('ab_tests',
    # sa.Column('id', sa.CHAR(length=32), nullable=False),
    # sa.Column('template_id', sa.CHAR(length=32), nullable=False),
    # sa.Column('version_a_id', sa.CHAR(length=32), nullable=False),
    # sa.Column('version_b_id', sa.CHAR(length=32), nullable=False),
    # sa.Column('traffic_ratio', sa.FLOAT(), nullable=False),
    # sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('ended_at', sa.DATETIME(), nullable=True),
    # sa.Column('version_a_calls', sa.INTEGER(), nullable=False),
    # sa.Column('version_b_calls', sa.INTEGER(), nullable=False),
    # sa.Column('version_a_avg_quality', sa.FLOAT(), nullable=False),
    # sa.Column('version_b_avg_quality', sa.FLOAT(), nullable=False),
    # sa.Column('winner_version_id', sa.CHAR(length=32), nullable=True),
    # sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], name=op.f('fk_ab_tests_template_id_prompt_templates')),
    # sa.ForeignKeyConstraint(['version_a_id'], ['prompt_versions.id'], name=op.f('fk_ab_tests_version_a_id_prompt_versions')),
    # sa.ForeignKeyConstraint(['version_b_id'], ['prompt_versions.id'], name=op.f('fk_ab_tests_version_b_id_prompt_versions')),
    # sa.ForeignKeyConstraint(['winner_version_id'], ['prompt_versions.id'], name=op.f('fk_ab_tests_winner_version_id_prompt_versions')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_tests'))
    # )
    # op.create_table('prompt_templates',
    # sa.Column('id', sa.CHAR(length=32), nullable=False),
    # sa.Column('scene', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    # sa.Column('description', sa.TEXT(), nullable=True),
    # sa.Column('current_version_id', sa.CHAR(length=32), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.ForeignKeyConstraint(['current_version_id'], ['prompt_versions.id'], name=op.f('fk_prompt_templates_current_version_id_prompt_versions')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    # sa.UniqueConstraint('scene', name=op.f('uq_prompt_templates_scene'))
    # )
    # ### end Alembic commands ###
