"""add status to pyramid_node

Revision ID: 82e338d8125c
Revises: 25303b564393
Create Date: 2026-02-12 14:46:33.875346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e338d8125c'
down_revision = '25303b564393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
