"""add_ai_suggestion_and_content_metadata

Revision ID: 847c2bfd7a59
Revises: 21819aba214f
Create Date: 2026-02-14 18:07:53.226457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847c2bfd7a59'
down_revision = '21819aba214f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_suggestions'))
    )
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_suggestions_input_hash'), ['input_hash'], unique=False)

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('health_reports', schema=None) as batch_op:
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('SCHEDULED', 'MANUAL', 'TRIGGERED', 'EVOLUTION_CYCLE', name='healthreporttype'),
               existing_nullable=False)

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('health_reports', schema=None) as batch_op:
        batch_op.alter_column('report_type',
               existing_type=sa.Enum('SCHEDULED', 'MANUAL', 'TRIGGERED', 'EVOLUTION_CYCLE', name='healthreporttype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('ai_metadata')

    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_suggestions_input_hash'))

    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
