"""add template_id to information_sources

Revision ID: 912e7d453313
Revises: e89853207c2b
Create Date: 2026-02-14 00:02:02.452097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912e7d453313'
down_revision = 'e89853207c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
