"""add_node_stats_and_relation_fields

Revision ID: a6d116f60aae
Revises: 5d78fcb79c09
Create Date: 2026-02-13 16:50:52.292956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d116f60aae'
down_revision = '5d78fcb79c09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_metrics_created_at'))
        batch_op.drop_index(batch_op.f('idx_api_metrics_endpoint_time'))

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_content_items_status'))
        batch_op.drop_index(batch_op.f('idx_content_items_title'))

    with op.batch_alter_table('content_node_relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_content_node_relations_content_id_content_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_content_node_relations_node_id_pyramid_nodes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_content_node_relations_content_id_content_items'), 'content_items', ['content_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_content_node_relations_node_id_pyramid_nodes'), 'pyramid_nodes', ['node_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_error_records_type_time'))

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sources_status_health'))

    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_prompt_versions_template'))

    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_content_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_validation_results_overall_score'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_validation_results_overall_score'), ['overall_score'], unique=False)

    with op.batch_alter_table('pyramid_nodes', schema=None) as batch_op:
        batch_op.drop_column('last_content_at')
        batch_op.drop_column('content_count')

    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_prompt_versions_template'), ['template_id', 'version'], unique=False)

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sources_status_health'), ['status', 'health_score'], unique=False)

    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_error_records_type_time'), ['error_type', 'created_at'], unique=False)

    with op.batch_alter_table('content_node_relations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_content_node_relations_node_id_pyramid_nodes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_content_node_relations_content_id_content_items'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_content_node_relations_node_id_pyramid_nodes'), 'pyramid_nodes', ['node_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_content_node_relations_content_id_content_items'), 'content_items', ['content_id'], ['id'])
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('source')

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_content_items_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('idx_content_items_status'), ['status'], unique=False)

    with op.batch_alter_table('api_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_metrics_endpoint_time'), ['endpoint', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_metrics_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
