"""Add original_data to approvals

Revision ID: ae9906918925
Revises: 380c488b41f4
Create Date: 2026-02-12 10:10:04.901492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9906918925'
down_revision = '380c488b41f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
