"""add_lifecycle_fields_to_source

Revision ID: d6135342e520
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-14 11:14:22.557309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6135342e520'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_runs', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('trial_successes', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recovery_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.drop_column('recovery_count')
        batch_op.drop_column('trial_successes')
        batch_op.drop_column('trial_runs')

    # ### end Alembic commands ###
