"""add_knowledge_graph_models

Revision ID: d63d87e75256
Revises: 73190a229726
Create Date: 2026-02-21 00:57:21.808979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd63d87e75256'
down_revision = '73190a229726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('ai_model', sa.JSON(), nullable=True),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('last_content_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_knowledge_nodes_concept_id_concepts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_nodes'))
    )
    op.create_table('content_knowledge_relations',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_content_knowledge_relations_content_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], name=op.f('fk_content_knowledge_relations_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'node_id', name=op.f('pk_content_knowledge_relations'))
    )
    op.create_table('knowledge_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_type', sa.String(length=20), nullable=False),
    sa.Column('center_node_id', sa.Uuid(), nullable=True),
    sa.Column('ai_model', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['center_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_clusters_center_node_id_knowledge_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_clusters'))
    )
    op.create_table('knowledge_node_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('discovered_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_node_relations_source_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_node_relations_target_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_node_relations'))
    )
    op.create_table('source_knowledge_relations',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], name=op.f('fk_source_knowledge_relations_node_id_knowledge_nodes')),
    sa.ForeignKeyConstraint(['source_id'], ['information_sources.id'], name=op.f('fk_source_knowledge_relations_source_id_information_sources')),
    sa.PrimaryKeyConstraint('source_id', 'node_id', name=op.f('pk_source_knowledge_relations'))
    )
    op.create_table('cluster_node_memberships',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['knowledge_clusters.id'], name=op.f('fk_cluster_node_memberships_cluster_id_knowledge_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], name=op.f('fk_cluster_node_memberships_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'node_id', name=op.f('pk_cluster_node_memberships'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_node_memberships')
    op.drop_table('source_knowledge_relations')
    op.drop_table('knowledge_node_relations')
    op.drop_table('knowledge_clusters')
    op.drop_table('content_knowledge_relations')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
