"""add_ai_metrics_table

Revision ID: df696bfff2e7
Revises: e31ad0ac66ba
Create Date: 2026-02-18 22:18:38.134382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df696bfff2e7'
down_revision = 'e31ad0ac66ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_metrics'))
    )
    with op.batch_alter_table('ai_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_metrics_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_metrics_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_metrics_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('ai_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ai_metrics_status'))
        batch_op.drop_index(batch_op.f('ix_ai_metrics_module'))

    op.drop_table('ai_metrics')
    # ### end Alembic commands ###
