"""扩展 AISuggestion 模型

Revision ID: e31ad0ac66ba
Revises: 847c2bfd7a59
Create Date: 2026-02-18 12:12:45.982123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31ad0ac66ba'
down_revision = '847c2bfd7a59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), server_default='create_node', nullable=False, comment='操作类型: create_node/delete_node/update_node/split_node/merge_node/link_content/update_strategy/archive_content'))
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), server_default='pyramid_node', nullable=False, comment='目标实体类型: pyramid_node/information_source/content_item'))
        batch_op.add_column(sa.Column('target_id', sa.Uuid(), nullable=True, comment='目标实体 ID'))
        batch_op.add_column(sa.Column('target_name', sa.String(length=255), nullable=True, comment='目标名称（便于用户识别）'))
        batch_op.add_column(sa.Column('reason', sa.Text(), server_default='', nullable=False, comment='AI 生成的原因（人类可读）'))
        batch_op.add_column(sa.Column('params', sa.JSON(), server_default='{}', nullable=False, comment='执行参数（AI 可执行）'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='状态: pending/approved/executed/rejected'))
        batch_op.add_column(sa.Column('pyramid_id', sa.Uuid(), nullable=True, comment='关联的金字塔'))
        batch_op.add_column(sa.Column('source_id', sa.Uuid(), nullable=True, comment='关联的信息源'))
        batch_op.create_index(batch_op.f('ix_ai_suggestions_status'), ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_ai_suggestions_source_id_information_sources'), 'information_sources', ['source_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_ai_suggestions_pyramid_id_pyramids'), 'pyramids', ['pyramid_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ai_suggestions_pyramid_id_pyramids'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ai_suggestions_source_id_information_sources'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_suggestions_status'))
        batch_op.drop_column('source_id')
        batch_op.drop_column('pyramid_id')
        batch_op.drop_column('status')
        batch_op.drop_column('params')
        batch_op.drop_column('reason')
        batch_op.drop_column('target_name')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
        batch_op.drop_column('action_type')

    # ### end Alembic commands ###
