"""Add template_id to sources

Revision ID: e89853207c2b
Revises: a6d116f60aae
Create Date: 2026-02-13 23:59:23.034836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89853207c2b'
down_revision = 'a6d116f60aae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['pyramid_nodes.id'], name=op.f('fk_node_relations_source_node_id_pyramid_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['pyramid_nodes.id'], name=op.f('fk_node_relations_target_node_id_pyramid_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_relations')),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'relation_type', name='uq_node_relation')
    )
    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information_sources', schema=None) as batch_op:
        batch_op.drop_column('template_id')

    op.drop_table('node_relations')
    # ### end Alembic commands ###
