"""Add iteration 4 models

Revision ID: ebdc791cf851
Revises: ae9906918925
Create Date: 2026-02-12 13:46:01.168088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdc791cf851'
down_revision = 'ae9906918925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('context_examples', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_evidence', sa.JSON(), nullable=True),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['previous_version_id'], ['concept_definitions.id'], name=op.f('fk_concept_definitions_previous_version_id_concept_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_definitions'))
    )
    with op.batch_alter_table('concept_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_definitions_term'), ['term'], unique=False)

    op.create_table('config_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_history'))
    )
    with op.batch_alter_table('config_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_history_config_key'), ['config_key'], unique=False)

    op.create_table('health_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('SCHEDULED', 'MANUAL', 'TRIGGERED', name='healthreporttype'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('pyramid_scores', sa.JSON(), nullable=False),
    sa.Column('source_health_score', sa.Float(), nullable=False),
    sa.Column('content_coverage_score', sa.Float(), nullable=False),
    sa.Column('hotspot_distribution', sa.JSON(), nullable=False),
    sa.Column('approval_backlog', sa.JSON(), nullable=False),
    sa.Column('crawl_stats', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_reports'))
    )
    op.create_table('hotspots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EMERGING', 'TRENDING', 'MATURE', 'COOLING', 'ARCHIVED', name='hotspotstatus'), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('recent_7d_count', sa.Integer(), nullable=False),
    sa.Column('previous_7d_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('display_priority', sa.Integer(), nullable=False),
    sa.Column('related_node_ids', sa.JSON(), nullable=True),
    sa.Column('related_content_ids', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_mentioned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotspots'))
    )
    with op.batch_alter_table('hotspots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotspots_topic_name'), ['topic_name'], unique=False)

    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks')),
    sa.UniqueConstraint('task_name', name=op.f('uq_scheduled_tasks_task_name'))
    )
    op.create_table('hotspot_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hotspot_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('STATUS_CHANGE', 'PRIORITY_CHANGE', 'MANUAL_UPDATE', 'SYSTEM_UPDATE', name='hotspoteventtype'), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('trigger_condition', sa.String(length=255), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspots.id'], name=op.f('fk_hotspot_events_hotspot_id_hotspots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotspot_events'))
    )
    op.create_table('strategy_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['information_sources.id'], name=op.f('fk_strategy_adjustments_source_id_information_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_adjustments'))
    )
    op.create_table('task_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], name=op.f('fk_task_executions_task_id_scheduled_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_executions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_executions')
    op.drop_table('strategy_adjustments')
    op.drop_table('hotspot_events')
    op.drop_table('scheduled_tasks')
    with op.batch_alter_table('hotspots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotspots_topic_name'))

    op.drop_table('hotspots')
    op.drop_table('health_reports')
    with op.batch_alter_table('config_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_history_config_key'))

    op.drop_table('config_history')
    with op.batch_alter_table('concept_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_definitions_term'))

    op.drop_table('concept_definitions')
    # ### end Alembic commands ###
