
import pytest
from hypothesis import given, strategies as st, settings, HealthCheck
from unittest.mock import AsyncMock, patch
import uuid

from app.models.source import InformationSource
from app.services.source_lifecycle_manager import SourceLifecycleManager

# Strategies for generating InformationSource states
source_status_st = st.sampled_from(["DISCOVERED", "VERIFYING", "ACTIVE", "MONITORING", "ADJUSTING", "DEAD"])
positive_int = st.integers(min_value=0, max_value=100)

@pytest.mark.asyncio
async def test_lifecycle_invariants(db_session):
    """
    Property: Ensure invalid state transitions don't happen silently or break invariants
    (This is a placeholder for property-based testing setup in async context)
    """
    pass

# Note: Full hypothesis testing with async database is complex. 
# We will focus on key properties using specific test cases generated by hypothesis
# but executed in a way compatible with pytest-asyncio.

@given(
    initial_status=source_status_st,
    error_count=positive_int,
    trial_runs=positive_int,
    trial_successes=positive_int
)
@settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
@pytest.mark.asyncio
async def test_on_crawl_success_resets_error_count(
    db_session, initial_status, error_count, trial_runs, trial_successes
):
    # Setup
    source = InformationSource(
        name="Prop Test Source",
        type="RSS",
        url="http://example.com",
        status=initial_status,
        error_count=error_count,
        trial_runs=trial_runs,
        trial_successes=trial_successes
    )
    db_session.add(source)
    await db_session.commit()
    await db_session.refresh(source)
    
    manager = SourceLifecycleManager(db_session)
    
    # Action
    await manager.on_crawl_success(str(source.id))
    
    # Invariant: Success always resets error count
    await db_session.refresh(source)
    assert source.error_count == 0

@given(initial_status=st.sampled_from(["ACTIVE", "MONITORING", "ADJUSTING"]))
@settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
@pytest.mark.asyncio
async def test_failure_increases_error_count(db_session, initial_status):
    # Setup
    source = InformationSource(
        name="Prop Test Source Fail",
        type="RSS",
        url="http://example.com",
        status=initial_status,
        error_count=0
    )
    db_session.add(source)
    await db_session.commit()
    
    manager = SourceLifecycleManager(db_session)
    
    # Action
    await manager.on_crawl_failure(str(source.id), "Error")
    
    # Invariant: Failure increases error count
    await db_session.refresh(source)
    assert source.error_count == 1
